name: test

on:
  push:
    branches:
      - master
      - node_upgrade
  pull_request:
    branches:
      - master
      - node_upgrade

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        #node-version: [ 10.x, 12.x, 14.x ]
        node-version: [ 8.x ]

    services:
      test_mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: meirim_test
        ports:
          - 33060:3306

    steps:
      - uses: actions/checkout@v2

      - name: use node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys:
            ${{ runner.OS }}-build-${{ env.cache-name }}
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: install dependencies
        run: npm install

      - name: create database
        run: mysql --host=localhost --port=33060 --password=meirim_test -e "CREATE DATABASE meirim_test character set UTF8 collate utf8_bin; SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY,',''));"

      - name: run migrations
        run: node node_modules/knex/bin/cli.js migrate:latest

      - name: test
        run: npm run test
